delete from agent;
insert into agent (id,name,superuser,username,passwd,active) values (1,'CARLOS CARBAJAL RODRIGUEZ',true,'agente1','ppl147',true);
insert into agent (id,name,superuser,username,passwd,active) values (2,'MARCO ANTONIO ALARCON ALDRETE',false,'agente2','rcm303',true);
insert into agent (id,name,superuser,username,passwd,active) values (3,'COMPARTIDO FERRE',false,'agente3','zja529',true);
insert into agent (id,name,superuser,username,passwd,active) values (4,'ROGELIO FRIAS HERMOSILLO',false,'agente4','grx241',true);
insert into agent (id,name,superuser,username,passwd,active) values (5,'ISRAEL GONZALEZ',true,'agente5','bfw254',true);
insert into agent (id,name,superuser,username,passwd,active) values (6,'NANCY ALVAREZ',false,'agente6','gxq553',true);
insert into agent (id,name,superuser,username,passwd,active) values (7,'LIBRE',false,'agente7','jnl606',true);
insert into agent (id,name,superuser,username,passwd,active) values (8,'HECTOR VAZQUEZ',false,'agente8','pym256',true);
insert into agent (id,name,superuser,username,passwd,active) values (9,'LIBRE',false,'agente9','rpb912',true);
insert into agent (id,name,superuser,username,passwd,active) values (10,'DAVID CRUZ',false,'agente10','trh687',true);
insert into agent (id,name,superuser,username,passwd,active) values (11,'MIGUEL ANGEL SANCHEZ',false,'agente11','lvp830',true);
insert into agent (id,name,superuser,username,passwd,active) values (12,'ROMAN VARGAS',false,'agente12','rlp741',true);
insert into agent (id,name,superuser,username,passwd,active) values (13,'RAMON JIMENEZ',false,'agente13','pxb436',true);
insert into agent (id,name,superuser,username,passwd,active) values (14,'LIBRE',false,'agente14','hqv816',true);
insert into agent (id,name,superuser,username,passwd,active) values (15,'DAVID JUAN GARCIA CRUZ',false,'agente15','ako249',true);
insert into agent (id,name,superuser,username,passwd,active) values (16,'LUIS MANUEL SANCHEZ CRUZ',false,'agente16','xzg743',true);
insert into agent (id,name,superuser,username,passwd,active) values (17,'JORGE RUEDA',false,'agente17','wux983',true);
insert into agent (id,name,superuser,username,passwd,active) values (18,'ARTURO ALEJANDRO RUIZ LEON',false,'agente18','cyr773',true);
insert into agent (id,name,superuser,username,passwd,active) values (19,'MARVIN CASTILLO GUILLEN',false,'agente19','xhl554',true);
insert into agent (id,name,superuser,username,passwd,active) values (20,'LIBRE',false,'agente20','xqp573',true);
insert into agent (id,name,superuser,username,passwd,active) values (21,'CALZADA JAL',false,'agente21','kiy276',true);
insert into agent (id,name,superuser,username,passwd,active) values (22,'CALZADA MTY',false,'agente22','zae854',true);
insert into agent (id,name,superuser,username,passwd,active) values (23,'ANDRES LOPEZ MAGAÑA',false,'agente23','hnd632',true);
insert into agent (id,name,superuser,username,passwd,active) values (24,'ALONSO MARTIN CASTAÑEDA VARGAS',false,'agente24','zcn359',true);
insert into agent (id,name,superuser,username,passwd,active) values (25,'DIEGO VICENTEÑO ORTIZ',false,'agente25','dfe938',true);
insert into agent (id,name,superuser,username,passwd,active) values (26,'DAVID MEZA',false,'agente26','gkl942',true);
insert into agent (id,name,superuser,username,passwd,active) values (27,'LIBRE',false,'agente27','pcw394',true);
insert into agent (id,name,superuser,username,passwd,active) values (28,'RAFAEL HERRERA DE LA FUENTE',false,'agente28','ncq319',true);
insert into agent (id,name,superuser,username,passwd,active) values (29,'EDGAR GONZALEZ',false,'agente29','ctw332',true);
insert into agent (id,name,superuser,username,passwd,active) values (30,'LIBRE',false,'agente30','yky930',true);
insert into agent (id,name,superuser,username,passwd,active) values (32,'OBED ARELLANO HURTADO',false,'agente32','ydm347',true);
insert into agent (id,name,superuser,username,passwd,active) values (33,'FCO. ARMANDO GARCIA CRUZ.',false,'agente33','caw914',true);
insert into agent (id,name,superuser,username,passwd,active) values (34,'JESUS GAMANIEL LOPEZ BELTRAN',false,'agente34','onq830',true);
insert into agent (id,name,superuser,username,passwd,active) values (43,'GUSTAVO SAINZ',false,'agente43','lgi102',true);
insert into agent (id,name,superuser,username,passwd,active) values (55,'SILVIA',false,'agente55','uhv171',true);
insert into agent (id,name,superuser,username,passwd,active) values (67,'Laura',false,'agente67','ymn929',true);
insert into agent (id,name,superuser,username,passwd,active) values (70,'Carlos Carbajal Rodriguez',true,'agente70','mkj611',true);
insert into agent (id,name,superuser,username,passwd,active) values (99999,'Agente expo',true,'agente99999','irk791',true);
select * from agent;