delete from category;
insert into category (line,name,legacy_name,text,description,norder) values (1,'all','ALL','Todos','&nbsp;',0);
insert into category (line,name,legacy_name,text,description,norder) values (1,'paqs_promos','PAQS_PROMOS','Paquetes y promociones','&nbsp;',1);
insert into category (line,name,legacy_name,text,description,norder) values (2,'all','ALL','Todos','&nbsp;',0);
insert into category (line,name,legacy_name,text,description,norder) values (2,'paqs_promos','PAQS_PROMOS','Paquetes y promociones','&nbsp;',1);
insert into category (line,name,legacy_name,text,description,norder) values (3,'all','ALL','Todos','&nbsp;',0);
insert into category (line,name,legacy_name,text,description,norder) values (3,'paqs_promos','PAQS_PROMOS','Paquetes y promociones','&nbsp;',1);
insert into category (line,name,legacy_name,text,description,norder) values (4,'all','ALL','Todos','&nbsp;',0);
insert into category (line,name,legacy_name,text,description,norder) values (4,'paqs_promos','PAQS_PROMOS','Paquetes y promociones','&nbsp;',1);
insert into category (line,name,legacy_name,text,description,norder) values (5,'all','ALL','Todos','&nbsp;',0);
insert into category (line,name,legacy_name,text,description,norder) values (5,'paqs_promos','PAQS_PROMOS','Paquetes y promociones','&nbsp;',1);
insert into category (line,name,legacy_name,text,description,norder) values (6,'all','ALL','Todos','&nbsp;',0);
insert into category (line,name,legacy_name,text,description,norder) values (6,'paqs_promos','PAQS_PROMOS','Paquetes y promociones','&nbsp;',1);
insert into category (line,name,legacy_name,text,description,norder) values (7,'all','ALL','Todos','&nbsp;',0);
insert into category (line,name,legacy_name,text,description,norder) values (7,'paqs_promos','PAQS_PROMOS','Paquetes y promociones','&nbsp;',1);
insert into category (line,name,legacy_name,text,description,norder) values (8,'all','ALL','Todos','&nbsp;',0);
insert into category (line,name,legacy_name,text,description,norder) values (8,'paqs_promos','PAQS_PROMOS','Paquetes y promociones','&nbsp;',1);
insert into category (line,name,legacy_name,text,description,norder) values (9,'all','ALL','Todos','&nbsp;',0);
insert into category (line,name,legacy_name,text,description,norder) values (9,'paqs_promos','PAQS_PROMOS','Paquetes y promociones','&nbsp;',1);
select * from category;