delete from client;
insert into client (id,name,agent,price_list,username,passwd,active) values (33333,'CLIENTE EXPO 3',99999,3,'cliente33333','cof140',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (44444,'CLIENTE EXPO 4',99999,4,'cliente44444','ont974',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (1,'FERREMAYOREO DE OCCIDENTE, S.A. DE C.V.',5,5,'cliente1','zpq821',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (2,'FERRETERIA INDAR, S.A. DE C.V.',11,4,'cliente2','snp183',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (3,'EQUIPOS INDUSTRIALES DE FLUIDOS,S.A.DE C.V.',1,3,'cliente3','mhg403',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (4,'FERRETERA PRADO S.A. DE C.V.',1,3,'cliente4','spj813',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (5,'FERRETERA Y TORNILLERIA ZAPATA, S.A. DE C.V.',2,4,'cliente5','ajc318',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (6,'CREAR HOGAR, S.A. DE C.V.',1,4,'cliente6','vmh803',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (7,'FERRETERA ELIZONDO HERMANOS, S. A.',34,4,'cliente7','ucd770',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (8,'FERRETERIA TICOS S.A. DE C.V.',1,4,'cliente8','ogt706',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (9,'HERRAMIENTAS LEO, S.A.DE.C.V.',32,3,'cliente9','zia413',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (10,'FERRETERIA Y PINTURAS GUEVARA, S.A. DE C.V.',34,4,'cliente10','qvc954',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (11,'FERREAGUA S.A. DE C.V.',2,4,'cliente11','irj999',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (12,'FERRECSA, S.A. DE C.V.',6,6,'cliente12','euh744',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (13,'INSUMOS Y HERRAMIENTAS DEL NORTE, S.A. DE C.V.',11,4,'cliente13','zrx218',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (14,'FERNANDO RAFAEL COVARRUBIAS JARA',32,4,'cliente14','mpe800',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (15,'BALEROS BANDAS Y TORNILLOS, S.A. DE C.V.',2,4,'cliente15','gxb161',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (16,'MALDONADO BRACAMONTE MARIA  MIREILLE DEL JESUS',1,4,'cliente16','ldo570',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (17,'SERVI-EQUIPOS DE SOLDADURA S.A DE C.V.',11,4,'cliente17','ehz353',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (19,'MARY FANY VALLE SANCHEZ',8,4,'cliente19','shc748',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (20,'DORA MA. SERRANO GONZALEZ',32,3,'cliente20','yki662',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (21,'CHS, S.A. DE C.V.',2,1,'cliente21','mpb205',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (22,'DETEK INTERNACIONAL, S.A. DE C.V.',1,3,'cliente22','szp159',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (23,'GUILLERMO CARROLL GARIBAY',1,1,'cliente23','raj926',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (24,'JOSE GAMEZ JIMENEZ',11,3,'cliente24','fve358',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (25,'ANTONIO VALDES VIZCARRA',2,4,'cliente25','kff144',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (26,'FERRETERA KIMURA S.A. DE C.V.',33,8,'cliente26','jhn118',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (27,'FERRETERA KIMURA S.A. DE C.V.',32,8,'cliente27','eec575',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (28,'JULIAN TREJO HERNANDEZ',26,4,'cliente28','mzc214',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (29,'ANASTASIO PEREZ HERNANDEZ',1,2,'cliente29','gtv134',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (30,'GRACIA GUADALUPE MELIN GAXIOLA',2,3,'cliente30','pmz389',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (31,'HERRAMIENTAS Y SERVICIOS DE LEON, S.DE R.L. DE C.V',32,3,'cliente31','ivq562',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (32,'FERRETERIA JUNCO, S.A',26,3,'cliente32','nip950',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (33,'TALLER Y REFACCIONES ALEJANDRO,S.A DE C.V.',11,3,'cliente33','sqn187',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (34,'FERREABASTECEDORA INDUSTRIAL, S.A DE C.V.',10,4,'cliente34','lkm511',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (35,'MANGUERAS Y CONEXIONES HIDRAULICAS, S.A DE C.V.',2,4,'cliente35','qso263',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (36,'MAYOREO FERRETERO ATLAS, S.A. DE C.V.',11,4,'cliente36','bxc932',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (37,'EQUIPOS HIDRAULICOS NACIONALES, S.A. DE C.V.',34,4,'cliente37','zsc886',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (38,'OCTAVIO AUGUSTO CALDERA MARTINEZ SALAS',11,4,'cliente38','cbj374',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (39,'TRACTORES Y EQUIPOS DE PUEBLA, S.A. DE C.V.',1,3,'cliente39','coa964',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (40,'FRANCISCO DEL RIO RUIZ',1,3,'cliente40','rbe526',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (41,'MARIA LISSETTE DAVILA GARCIA',32,4,'cliente41','dqn782',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (42,'FERRETERIA MALOVA, S.A. DE C.V.',2,1,'cliente42','qvy172',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (43,'HERRAMIENTAS Y EQUIPOS PROFESIONALES, S.A. DE C.V.',1,3,'cliente43','fed510',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (44,'HERRAMIENTAS Y REPARACIONES INDUSTRIALES,S.A. DE C.V.',8,3,'cliente44','nig552',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (45,'MOISES MORENO PATIÑO',8,2,'cliente45','vrk410',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (46,'CASA  JAD HERRAMIENTAS,S.A. DE C.V.',1,4,'cliente46','obb452',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (47,'CONCESIONES H, S. A. DE C. V.',2,3,'cliente47','fxz710',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (48,'FERNANDO GABRIEL PEREZ GUERRA',1,4,'cliente48','tiy147',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (49,'GERARDO YEPEZ GARCIA',1,1,'cliente49','qnk427',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (50,'PROVEEDOR FERRETERO,  S.A. DE C.V.',13,4,'cliente50','ahi577',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (51,'ADOLFO SANCHEZ GARCIA',1,3,'cliente51','jeu641',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (52,'ENRIQUE CIMENTAL GONZALEZ',1,3,'cliente52','vgj736',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (53,'MANGUERAS Y CONEXIONES HIDRAULICAS DE CHIHUAHU',4,3,'cliente53','ymo672',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (54,'EL TORNILLO MAGICO, S.A. DE C.V.',1,3,'cliente54','szq629',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (55,'DISTRIBUIDORA DE HERRAMIENTAS INDUST. DE OCCTE. S.A. DE C.V.',1,2,'cliente55','joo385',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (56,'BYMTESA DE MANZANILLO, S.A DE C.V.',32,4,'cliente56','xel865',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (57,'FERRETERIA SAN CARLOS, S.A. DE C.V.',34,3,'cliente57','fbr733',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (58,'COMERCIALIZADORA DE HERRAMIENTAS Y EQUIPOS FINOS SA DE CV',26,4,'cliente58','lkd744',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (59,'ABASTECEDORA POTOSINA DE HERRAMIENTAS,S.A DE C.V',1,3,'cliente59','zat786',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (60,'IRMA CELINA ARELLANO AVILA',11,4,'cliente60','hvy164',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (61,'MAGDALENA YOLANDA DEL VALLE LOPEZ',34,4,'cliente61','gsi379',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (62,'UNION FLORES FERRETERA, S.A DE C.V.',34,3,'cliente62','jhi915',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (63,'HERRAMIENTAS LIBERTAD, S.A. DE C.V.',11,3,'cliente63','wsr139',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (64,'FERROXCO, S.A DE C.V.',2,4,'cliente64','wmb225',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (65,'AURORA AIDE ARMENTA ZAVALA',2,3,'cliente65','nwv189',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (66,'CARLOS CARBAJAL RODRIGUEZ',1,1,'cliente66','hzt620',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (67,'COMERCIALIZADORA ESTOKEY S.A. DE C.V.',26,2,'cliente67','qjo150',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (68,'COMERCIALIZADORA MAQ-INTER, S.A. DE C.V.',1,4,'cliente68','gmq568',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (69,'ALEJANDRO ARIAS SANCHEZ, S.A.',1,2,'cliente69','ura486',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (70,'MULTIHERRAMIENTAS INDUSTRIALES, S.A. DE C.V.',32,3,'cliente70','wpx572',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (71,'GRUPO CONTINENTE INTERNACIONAL, S.A. DE C.V.',1,4,'cliente71','bpj390',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (72,'MARIA ELENA CARRASCO BARRON',1,3,'cliente72','utt962',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (73,'LLANTAS Y REFACCIONES AGRICOLAS, S.A. DE C.V.',11,4,'cliente73','bwe507',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (74,'HERRAMIENTAS CASA MIRANDA, S.A. DE C.V.',26,3,'cliente74','hdk403',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (75,'CELIA BUGARIN DOMINGUEZ',10,4,'cliente75','qxx184',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (76,'RODAMIENTOS Y REPRESENTACIONES INDUSTRIALES, S.A. DE C.V.',4,4,'cliente76','upa887',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (77,'CARLOS CASAS MONSIVAIS',1,1,'cliente77','wci981',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (78,'FERRELAMINAS, S.A. DE C.V.',1,1,'cliente78','mus289',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (79,'GEMPSA HERRAMIENTAS PLOMERIA Y SIMILARES, S.A. DE C.V.',1,1,'cliente79','aoe754',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (80,'RICARDO EFREN CAMPOS HERNANDEZ',26,3,'cliente80','qvp134',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (81,'PENELOPE ROCIO VIAMONTE GUERRERO',1,4,'cliente81','ulb629',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (82,'JUAN ROMAN VARGAS GARCIA',5,3,'cliente82','rez708',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (83,'MIGUEL ANGEL VILLASEÑOR VALLEJO',1,3,'cliente83','cec138',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (84,'FLORENCIO LOPEZ CARMONA',1,4,'cliente84','vjx509',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (85,'CINTHYA VARGAS NANDO',11,1,'cliente85','ikp355',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (86,'ELIM DOMINGO MONTIEL CEBADA',1,3,'cliente86','gmc998',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (87,'FERRETERIA MODELO MEXICO, S.A. DE C.V.',6,4,'cliente87','oso958',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (88,'MERCADOTECNIA ITC',1,2,'cliente88','gka722',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (89,'MYR DEL GOLFO, S.A. DE.C.V.',1,4,'cliente89','jmh496',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (90,'RYV DEL NORTE, S.A. DE C.V.',1,3,'cliente90','fsl206',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (91,'ABASTECEDORA FERRETERA DON CARLOS, S.A DE C.V.',1,3,'cliente91','yvf878',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (92,'EIF FERRETERO, S.A. DE C.V.',1,1,'cliente92','jjf533',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (93,'YOLANDA JIMENEZ ZERTUCHE',1,3,'cliente93','ncr981',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (94,'DAVID ISRAEL GUEVARA DEL VALLE',34,4,'cliente94','fec272',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (95,'SURTIDORA TAPATIA DE INDUSTRIAS, S.A. DE C.V.',1,5,'cliente95','gxt289',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (96,'HERMELINDA VILLA MARISCAL',1,1,'cliente96','jwt789',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (97,'COMPAÑIA POWER TOOLS S.A. DE C.V.',1,1,'cliente97','uyx636',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (98,'FERREKABE, S.A. DE C.V.',26,3,'cliente98','efi458',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (99,'MARIA GUADALUPE LANGLE RODRIGUEZ',1,1,'cliente99','yqs908',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (100,'LIDER COMERCIAL MOTOR S.A. DE C.V.',26,1,'cliente100','oix748',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (101,'CANDIDO REYES CORDERO',26,3,'cliente101','wlj707',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (102,'MARTHA PATRICIA RIVAS ROJAS',10,4,'cliente102','zls116',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (103,'MARCELA ROSALIA ARAGON TORRES',1,3,'cliente103','zbo976',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (104,'SILVIA VALDEZ MARTINEZ',26,3,'cliente104','eoa644',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (105,'ABASTECEDORA DE SOLDADURAS Y HERRAMIENTAS SA DE CV',34,3,'cliente105','rtr528',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (106,'CERON HERRAMIENTAS DE HIDALGO S.A. DE C.V.',11,4,'cliente106','lib913',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (107,'CIA MERCANTIL FERRETERA,S.A. DE C.V.',1,4,'cliente107','zey820',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (108,'JULIO CESAR AZPEITIA HERNANDEZ',1,1,'cliente108','sqk750',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (109,'MAGUS, S.A. DE C.V.',11,3,'cliente109','hkm925',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (110,'CONSECIONARIA ALEJANDRO S.A. DE C.V.',10,4,'cliente110','ixh271',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (111,'R. SAMANO Y CIA., S.A. DE C.V.',8,4,'cliente111','kfo233',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (112,'TOMACO, S.A. DE C.V.',2,4,'cliente112','ebu865',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (113,'MARINES ESPINOZA JUAN JOSE',8,4,'cliente113','ack163',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (114,'GRUPO FERRETERO BOSS S.A. DE C.V.',26,4,'cliente114','zgf389',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (115,'FERROMAX S.A. DE C.V.',1,3,'cliente115','jva757',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (116,'ALFONSO MORALES PINEDA',1,1,'cliente116','grn925',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (117,'CECILIA SHIMIZU YAMASAKI',26,4,'cliente117','ixi332',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (118,'FERRE. V.K. SA DE CV',6,3,'cliente118','wfz189',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (119,'MARIA CLAUDIA AGUIÑAGA HERNANDEZ',1,3,'cliente119','bfz761',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (120,'ALAN FERNANDO SALAS AGUIÑAGA',26,3,'cliente120','fue748',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (121,'ALAN MISAEL PADILLA ROCHA',1,3,'cliente121','dzc257',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (122,'EUTIQUIO CASTILLO RUELAS',1,1,'cliente122','qsb206',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (123,'ANA MARIA PAREDES PICO',8,1,'cliente123','clc673',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (124,'ALMA ANGELICA FONSECA GOMEZ',8,1,'cliente124','tvy270',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (125,'FERRETERA Y BAÑOS AZTECA S.A. DE C.V.',26,4,'cliente125','zlz517',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (126,'FELICITAS LOPEZ MARTINEZ',1,2,'cliente126','gjm610',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (127,'FERRETERIA MODELO DEL BAJIO, S.A. DE C.V.',8,4,'cliente127','emt748',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (128,'FERRETERIA LA FRAGUA, S.A. DE C.V.',8,4,'cliente128','anc482',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (129,'TECNOHERRAMIENTAS SURTIDORA S DE RL DE CV',1,4,'cliente129','eba375',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (130,'GEMPSA HERRAMIENTAS PLOMERIA Y SIMILARES, S.A. DE C.V.',8,3,'cliente130','bcr529',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (131,'PEDRO ANTONIO ARIAS ARCHUNDIA',1,4,'cliente131','nkp832',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (132,'FILOGONIO AGUILAR OSEGUERA',1,2,'cliente132','qyt871',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (133,'ESCAMILLA REYES JUAN CARLOS',1,1,'cliente133','oge282',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (134,'CARLOS RAMIREZ BELLO',10,4,'cliente134','myd978',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (135,'SISTEMAS HIDRAULICOS DEL USUMACINTA S.A. DE C.V.',1,3,'cliente135','bar999',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (136,'MATERIALES DEL NORTE DE CUAUHTEMOC S.A. DE C.V',14,4,'cliente136','fog421',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (137,'VENTANAS CUAUHTEMOC  S.A. DE C.V',14,4,'cliente137','yll547',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (138,'SERVISOMEX, S.A. DE C.V.',4,4,'cliente138','kct654',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (139,'RAMON ALARCON DELGADO',2,1,'cliente139','ubp947',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (140,'JOSE HUMBERTO MENDIVIL CASTRO',11,1,'cliente140','hde535',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (141,'FERRETERIA MIXCOAC, S.A. DE C.V.',26,4,'cliente141','brh815',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (142,'MAQUINARIA DEL PACIFICO, S.A. DE C.V.',10,4,'cliente142','klc775',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (143,'LARD EQUIPOS MECANICOS S.A. DE C.V.',32,3,'cliente143','svd542',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (144,'NUEVA IXTLERA DE LA SIERRA  DE CHIHUAHUA, S.A.',11,2,'cliente144','vbv740',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (145,'OSCAR CADENA S.A. DE C.V.',8,4,'cliente145','ybm616',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (146,'CARLOS ROBERTO SILVA VENZOR',1,1,'cliente146','tap780',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (147,'RAMON RUIZ LOPEZ',4,3,'cliente147','qok118',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (148,'ELECTROMAQUINARIA DE VICTORIA S.A. DE C.V.',26,1,'cliente148','lpf210',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (149,'ALFREDO GONZALEZ TORRES',32,3,'cliente149','jbj963',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (150,'COMERCIALIZADORA LA CASA AMARILLA DE ATOTONILCO S.A DE C.V.',32,4,'cliente150','sul118',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (151,'HERRAMIENTAS INDUSTRIALES DE CHIHUAHUA, S.A. DE C.V.',11,4,'cliente151','wak357',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (152,'COORTIS S.A. DE C.V.',4,4,'cliente152','atd625',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (153,'ALFREDO HIDALGO CEJUDO',26,3,'cliente153','gar799',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (154,'ANASTASIO PEREZ HERNANDEZ',1,3,'cliente154','sdf760',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (155,'HOMERO HERNANDEZ DAVILA',4,4,'cliente155','jvo171',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (156,'FIERRO Y LAMINA DE LOS MOCHIS S.A. DE C.V.',2,4,'cliente156','waq858',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (157,'MA. CANDELARIA LUNA VIELMAS',1,3,'cliente157','xib661',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (158,'DOMINGUEZ GUTIERREZ MICAELA',10,4,'cliente158','kwo146',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (159,'JOSE GUADALUPE TORRES RODRIGUEZ',11,3,'cliente159','uhy424',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (160,'J. REFUGIO SANDOVAL APOLINAR',11,3,'cliente160','hff503',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (161,'SOLDADURAS Y EQUIPOS RAFE, S.A. DE C.V.',34,4,'cliente161','mbk125',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (162,'ROMERO GONZALEZ PAULA',11,1,'cliente162','azl642',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (163,'GUADALUPE IVONNE CARRASCO DAVALOS',4,3,'cliente163','uvt100',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (164,'MARIA GUADALUPE CARRILLO MIRELES',11,3,'cliente164','tbi369',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (165,'ACCESORIOS FORESTALES DEL SURESTE S.A. DE C.V.',1,3,'cliente165','qfj140',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (166,'REPRESENTACIONES INDUSTRIALES Y DISTRIBUCIONES, SA DE CV',11,4,'cliente166','yll831',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (167,'BRUNO ALEJANDRO ARELLANO AVILA',11,4,'cliente167','ifj996',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (168,'PEDRO REYES RODRIGUEZ',32,4,'cliente168','tix103',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (169,'JULIAN ZAMORA DE JESUS',11,3,'cliente169','qwl561',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (170,'FERRETERIA Y MATERIALES DEL CAMPO 8, S.A. DE C.V.',14,4,'cliente170','ofd681',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (171,'DANIELA ADRIANA RODRIGUEZ ABBUD',14,4,'cliente171','emu189',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (172,'JOSE ALFREDO ARAGON SALMERON',4,4,'cliente172','cwd905',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (173,'LETICIA CRUZ CHAVEZ',26,2,'cliente173','pzw786',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (174,'COMERCIALIZADORA DE BOMBAS Y MAQUINARIA SA DE CV',10,4,'cliente174','sjw686',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (175,'EQUIPOS Y HERRAMIENTAS HIDRAULICAS DE MONTERREY S.A DE C.V',34,4,'cliente175','nmf951',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (176,'JOSE ANTONIO ANCHONDO ARZAGA',4,4,'cliente176','uni590',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (177,'HILDA GONZALEZ MARTINEZ',26,2,'cliente177','wau805',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (178,'FERRERA HEMEGA S.A. DE C.V.',32,4,'cliente178','yfc686',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (179,'CENDIMEX S.A DE C.V',1,1,'cliente179','xll674',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (180,'EDITH CASTELLANOS REYNAGA',1,3,'cliente180','oni588',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (181,'PASTOR SOSA ZAMORA',32,4,'cliente181','sgc688',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (182,'FERRETERIA EL PALMARCITO S.A. DE C.V.',32,4,'cliente182','pda269',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (183,'REPRESENTACIONES INDUSTRIALES DINAMICAS, S.A. DE C.V.',10,4,'cliente183','mrw174',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (184,'MARIA LORENIA BONFIGLIO VALENZUELA',13,3,'cliente184','vys919',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (185,'CARLOS EDUARDO CORTEZ PULIDO',11,4,'cliente185','gaz671',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (186,'FERRETERIAS PRINEL S.A. DE C.V.',34,2,'cliente186','ehy102',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (187,'BASICOS AUTOMOTRICES,  S.A. DE C.V.',32,3,'cliente187','twn269',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (188,'HERRAJES Y SOLDADURAS DEL BAJIO, S.A. DE C.V.',26,4,'cliente188','rpx457',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (189,'TOOL CENTER, S.A. DE C.V.',11,3,'cliente189','ntj557',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (190,'AGUSTIN LUNA LOPEZ',34,2,'cliente190','vog240',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (191,'MAGDALENA RUBIO CARRILLO',2,4,'cliente191','ikn488',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (192,'LIGHT MACHINERY S.A. DE C.V.',34,4,'cliente192','xwc895',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (193,'ENGRACIA NUÑEZ VAZQUEZ',34,3,'cliente193','coh919',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (194,'FERRETERA CENTENARIO DE MONTERREY S.A DE C.V.',34,4,'cliente194','sof821',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (195,'MAQ Y MAQ S.A DE C.V.',34,4,'cliente195','zxb415',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (196,'FERRETERIA LA LIBRA S.A DE C.V',6,7,'cliente196','yak686',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (197,'FERRETERIA LA LIBRA S.A DE C.V',6,7,'cliente197','dzb936',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (198,'FERRETERIA LA LIBRA S.A DE C.V',6,7,'cliente198','cjf422',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (199,'DREY S.A DE C.V.',10,3,'cliente199','wbn633',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (200,'CASA MONROY S.A. DE C.V.',26,4,'cliente200','yxn204',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (201,'REFACCIONARIA ROGELIO S.A DE C.V',1,4,'cliente201','cqj627',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (202,'AIDA ARACELI CERVANTES SANTANA',6,4,'cliente202','yvk832',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (203,'SILVIA GARCIA QUEZADA',15,4,'cliente203','mfg272',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (204,'VIBRADORES DE MEXICO S.A DE C.V.',34,4,'cliente204','lwm287',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (205,'ANA BERTHA JIMENEZ BRAVO',11,4,'cliente205','goz163',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (206,'JORGE ANTONIO MAGALLANES MARTINEZ',10,4,'cliente206','hsx255',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (207,'BOMBAS Y MOTORES DE TECOMAN S.A DE C.V.',10,4,'cliente207','swg372',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (208,'EQUIPOS DE LIMPIEZA Y AUTOLAVADO S DE RL DE CV',10,4,'cliente208','tjj668',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (209,'MATERIALES ARANDINOS S.A DE C.V.',32,4,'cliente209','zog419',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (210,'G. ELECTROMECANICA Y CONTROL S.A DE C.V.',10,4,'cliente210','ydl193',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (211,'KRISS PRINCESA BACA REYES',4,3,'cliente211','kik397',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (212,'COMERCIAL FERRERAMA S.A DE C.V.',13,4,'cliente212','xgv108',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (213,'JUAN FERNANDO NUÑO COSIO',1,1,'cliente213','kvk300',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (214,'FRANCISCO JAVIER MARTINEZ BONFIGLIO',13,3,'cliente214','ram459',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (215,'MARIA DE LA CRUZ SANCHEZ CERVANTES',1,4,'cliente215','hag750',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (216,'JUAN CARLOS POLO GARCIA',1,4,'cliente216','nnp969',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (217,'JOSE LUIS SILVA LOPEZ',32,3,'cliente217','esm544',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (218,'EDUARDO ERNESTO ROMAN BAÑUELOS',1,4,'cliente218','yti210',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (219,'FERREMET S.A DE C.V .',6,4,'cliente219','xyu866',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (220,'PRODUCTOS Y SERVICIOS DE VERACRUZ S.A DE C.V.',16,3,'cliente220','xhh445',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (221,'LUIS MANUEL BELMONTE TAFOLLA',1,4,'cliente221','cjm557',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (222,'CARLOS NAIM ALI MENDIOLA',34,4,'cliente222','nyd339',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (223,'COMERCIAL AGRICOLA Y GANADERA DE TOLUCA S.A DE C.V',26,4,'cliente223','grm809',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (224,'GUILLERMO RENE GAMBOA ACOSTA',11,1,'cliente224','abn276',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (225,'FERRETERIA VIRAMONTES S.A DE C.V.',1,3,'cliente225','wsk586',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (226,'MAQUINARIA Y EQUIPO HERMANOS ESCOBEDO S.A DE C.V.',1,4,'cliente226','hah153',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (227,'MAQUINAS Y HERRAMIENTAS DE MEXICO S.A DE C.V',32,4,'cliente227','iqn113',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (228,'LAZARO ANDRES VAZQUEZ GONZALEZ',11,4,'cliente228','jrj938',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (229,'REFACCIONES Y MOTORES ARIAS S.A DE C.V',5,3,'cliente229','djc758',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (230,'MAQUINARIA PARA CONSTRUCCION DIMEX S.A DE C.V.',34,4,'cliente230','dlj775',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (231,'OCHOA SOLIS ALFREDO',32,3,'cliente231','nim458',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (232,'ARMINDA LIDIA URBINA HERNANDEZ',26,4,'cliente232','jbe274',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (233,'GRUPO CANHESUR, S.A. DE C.V.',15,3,'cliente233','oqc301',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (234,'OXIGENO Y ELECTRODOS DE JALISCO, S.A.',10,4,'cliente234','ywy326',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (235,'AC MAQUINARIA S.A DE C.V.',5,4,'cliente235','uzp556',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (236,'ANA CECILIA CASTRO DE LA TORRE',1,4,'cliente236','lns592',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (237,'LOGIS TRADING CO., S.A. DE C.V.',1,1,'cliente237','zsi521',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (238,'LUIS BERNARDO FOSADO FRIAS',5,3,'cliente238','ooy915',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (239,'JE&S NEGOCIOS, S.A. DE C.V.',1,4,'cliente239','dfe522',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (240,'PLANTAS ELECTRICAS LUMA SA DE CV',34,4,'cliente240','oka612',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (241,'OMAR GARCIA SAENZ',34,4,'cliente241','dne324',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (242,'EDGAR TORRES RAYON',26,4,'cliente242','fbd231',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (243,'GRUPO FERREMARCA DE MEXICO S.A DE C.V.',17,4,'cliente243','abx218',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (244,'JOSE ALFREDO JAIME RIOS',32,3,'cliente244','kow504',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (245,'JOSE DANIEL VERGARA VALERIO',11,4,'cliente245','lrz841',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (246,'VICTOR JOSE DE JESUS CABEZUD VELAZQUEZ',10,4,'cliente246','xqk225',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (247,'MAQUINARY AND TOOLS CONSTRUCTION STORE S.A. DE C.V.',26,1,'cliente247','rap626',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (248,'BERIND, S.A. DE C.V.',1,4,'cliente248','bjy603',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (249,'MEMBRANAS PLASTICAS DE OCCIDENTE S.A. DE C.V.',1,3,'cliente249','fze692',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (250,'RAUL TORRES ESPINOZA',5,3,'cliente250','wes737',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (251,'DISTRIBUIDORA CRUZA, S.A.',26,4,'cliente251','tes297',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (252,'EDGAR TORRES RAYON',26,3,'cliente252','ykn214',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (253,'LUIS GERARDO GONZALEZ OLIVA',34,4,'cliente253','ybg593',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (254,'DISTRIBUIDORA DE REPUESTOS INDUSTRIALES, S.A. DE C.V.',26,3,'cliente254','bax620',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (255,'MARIA VIRGINIA DEMOSS AGUAYO',13,4,'cliente255','dcm311',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (256,'JUAN CAMACHO CORREA',1,2,'cliente256','hdq676',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (257,'CASA GUERRA DE MONTERREY S.A. DE C.V.',34,4,'cliente257','mrs649',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (258,'FERREAGRO DE GUAMUCHIL SA DE CV',2,4,'cliente258','rua561',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (259,'FERRETERIA LA CARREDANA S.A. DE C.V.',8,4,'cliente259','quj165',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (260,'FERREMATERIALES Y ACEROS ENNS S.A. DE C.V.',14,4,'cliente260','vrt524',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (261,'HUGO ALBERTO PRESAS RIOS',1,4,'cliente261','grv415',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (262,'HUGO CESAR DIAZ ARROYO',1,3,'cliente262','cfg356',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (263,'STARS LIGHTING SYSTEM, S.A. DE C.V.',12,4,'cliente263','oxw270',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (264,'VERONICA DEL ROCIO ROSALES GUTIERREZ',11,4,'cliente264','ppe499',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (265,'REFACCIONES Y SERVICIOS BARRERA S.A. DE C.V',26,3,'cliente265','ord419',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (266,'AMERICAN SD POWER, INC.',1,1,'cliente266','djm693',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (267,'CASA OSGUEL S.A. DE C.V.',34,4,'cliente267','ldm503',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (268,'MATERIALES, ACEROS TUCAN, S.A. DE C.V.',16,3,'cliente268','rgp889',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (269,'SOLDADURA, EQUIPO Y CONSTRUCCION, S.A. DE C.V.',11,4,'cliente269','uvr183',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (270,'JORGE ESTEBAN LAGARDA LEYVA',2,4,'cliente270','euw927',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (271,'ELECTRODOS Y DISTRIBUCIONES, S.A. DE C.V.',34,4,'cliente271','nag355',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (272,'MARTINEZ DURAN HERIBERTA',2,4,'cliente272','vxz993',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (273,'VIBROMAQUINARIA S.A. DE C.V.',6,4,'cliente273','hwo118',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (274,'FELIPE GARCIA GARCIA',23,3,'cliente274','xpa413',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (275,'ENLACE COMERCIAL FERRETERO S.A. DE C.V.',11,4,'cliente275','rlo724',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (276,'ARA DE SALTILLO, S.A. DE C.V.',34,4,'cliente276','kyb126',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (277,'FERRERIVAS, S.A. DE C.V.',26,4,'cliente277','lld284',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (278,'BOMBAS Y MOTORES DE COLIMA S.A. DE C.V.',11,3,'cliente278','mpq401',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (279,'JUANA VALDES GARCIA',5,4,'cliente279','kgq286',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (280,'MARIA DE LOS ANGELES FLORES PROA',12,3,'cliente280','cqn452',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (281,'GRUPO INDUSTRIAL ANFE, S.A. DE C.V.',26,4,'cliente281','ryy105',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (282,'ISRAEL  CORTES BRAMARDI',34,3,'cliente282','ygt927',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (283,'TECNOJARDIN S.A. DE C.V.',1,4,'cliente283','ouk679',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (284,'ROSALINDA MELÉNDEZ GARZA',12,3,'cliente284','iks253',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (285,'CALDERON SOTO SUSANA',32,4,'cliente285','xmc820',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (286,'ASESORES EN MANTENIMIENTO AMBIENTAL S.A. DE C.V.',11,4,'cliente286','fyr947',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (289,'ALBERTO TOPETE URREA',11,4,'cliente289','fau772',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (290,'FELICITAS ALVARADO PERAZA',2,1,'cliente290','ugr482',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (291,'MEGA SERVICIOS PARA EL CONSTRUCTOR S.A. DE C.V.',15,4,'cliente291','kin309',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (292,'TRACTORES Y EQUIPOS DE PUEBLA S.A. DE C.V.',15,4,'cliente292','znx443',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (293,'RENE OMAR RODRIGUEZ RAMIREZ',12,4,'cliente293','ogz823',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (294,'PATRICIA ALFARO GARCIA',26,3,'cliente294','evi412',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (295,'GRUPO VALEY MEXICO S.A. DE C.V.',11,4,'cliente295','yzh167',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (296,'REFACCIONES MAS FACIL, S.A. DE C.V.',2,4,'cliente296','vnf582',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (297,'ALFREDO AGATON CORTEZ',10,4,'cliente297','vnz569',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (298,'HECTOR VAZQUEZ VELASCO',8,4,'cliente298','gpi538',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (299,'DAVID MEZA QUINTERO',26,4,'cliente299','hih123',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (300,'COMERCIAL DE TABASCO S.A. DE C.V.',15,4,'cliente300','jwa330',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (301,'RAPIDFAHR, S.A.',26,4,'cliente301','abj661',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (302,'MARIA LUISA RODRIGUEZ RODRIGUEZ',15,4,'cliente302','hva801',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (303,'RUBEN HERRERA VARGAS',6,4,'cliente303','uku375',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (304,'BERTA AURORA MORAN HURTADO',34,4,'cliente304','ubx274',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (305,'CLAVOS NACIONALES MEXICO, S.A. DE C.V',26,3,'cliente305','nol733',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (306,'RAMON GERARDO ALARCON PALOMARES',2,4,'cliente306','sxp500',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (307,'FABRICA GENERAL DE MAQUINARIA Y CONTROL S.A. DE C.V.',26,4,'cliente307','cbh760',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (308,'GRUPO ALFA DE TOLUCA S.A. DE C.V',11,4,'cliente308','mrm926',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (309,'FERRETECNICA PEGASO S.A. DE C.V.',8,4,'cliente309','mkm415',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (310,'FELIPE GARCIA GARCIA',16,4,'cliente310','kya183',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (311,'ALFONSO HERRERA VARGAS',26,4,'cliente311','aqr954',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (312,'GRUPO FERRETERIA CALZADA, S.A. DE C.V.',21,4,'cliente312','mxx629',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (313,'FERRETERIA LA PASIEGA S.A. DE C.V.',32,4,'cliente313','taw999',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (314,'TRACSA, S.A. DE C.V.',1,4,'cliente314','hwt183',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (315,'FERRECOQUI S DE RL',24,4,'cliente315','kkl827',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (316,'EDGAR ALAN RODRIGUEZ RAMIREZ',34,3,'cliente316','aif557',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (317,'RENE OMAR RODRIGUEZ RAMIREZ',12,4,'cliente317','wmb983',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (318,'JOHANA MARLEN DURAN GARCIA',12,4,'cliente318','lwp163',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (319,'JORGE ALBERTO BOLIO MARIN',1,3,'cliente319','jfx884',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (320,'CENTRO FERRETERO CANDELARIA S.A. DE C.V.',24,4,'cliente320','siu706',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (321,'LUZ ADELA BELTRAN RAMOS',2,4,'cliente321','viw381',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (322,'ALEJANDRO RAMIREZ CERVANTES',1,4,'cliente322','zzp985',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (323,'JUDAS ARTURO LEPE ARELLANO',10,3,'cliente323','xhk813',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (324,'BASALDUA MENDEZ TOMAS',19,4,'cliente324','taa246',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (325,'DANIEL BARRERA MARTINEZ',5,3,'cliente325','ewm851',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (326,'HORACIO ARIAS ARCHUNDIA',26,4,'cliente326','jzf741',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (327,'SILVIA MARIA AYALA HERNANDEZ',8,3,'cliente327','uty912',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (328,'HERRAMIENTAS ACZ S.A. DE C.V',6,4,'cliente328','bos582',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (329,'VERENICE RAFAELA ENCINAS ALVAREZ',13,4,'cliente329','fyp789',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (330,'ACEROS Y HERRAJES S.A. DE C.V.',32,4,'cliente330','rsh713',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (331,'JUAN FELIPE CHAVEZ MORAN',11,4,'cliente331','yqe295',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (332,'GRUPO REALSA EN HERRAMIENTAS S.A. DE C.V.',24,4,'cliente332','xgn262',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (333,'LUIS EDUARDO BERUMEN ARTEAGA',11,3,'cliente333','zwf981',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (334,'GRUPO REALSA EN HERRAMIENTAS S.A. DE C.V.',24,4,'cliente334','hmu817',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (335,'COMPAÑIA FERNANDEZ DE MERIDA, S.A. DE C.V.',24,4,'cliente335','kyu519',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (336,'GRUPO FERRETERIA CALZADA, S.A. DE C.V',22,4,'cliente336','zhh203',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (337,'CENTRAL FERRETERA TREJO S.A. DE C.V.',8,4,'cliente337','env773',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (338,'JOSE RICARDO HERNANDEZ MARTINEZ',1,4,'cliente338','pbs837',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (339,'GRUPO REALSA EN HERRAMIENTAS S.A. DE C.V.',24,4,'cliente339','lfl396',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (340,'AISLANTES Y MAGNETOS TAPATIOS, S.A. DE C.V.',11,3,'cliente340','mtk126',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (341,'FERRETERIA Y ACEROS DE CELAYA, S.A. DE C.V.',11,4,'cliente341','qle161',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (342,'HERRAMIENTAS Y EQUIPOS INDUSTRIALES DE TULA, S.A. DE C.V.',11,4,'cliente342','xuk343',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (343,'HERRAMIENTAS Y SERVICIOS DE OBREGON S.A. DE C.V.',2,4,'cliente343','pmd615',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (344,'MARTHA VAZQUEZ CUEVAS',11,4,'cliente344','sxa525',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (345,'GRUPO FERRETERIA CALZADA S.A. De C.V.',22,4,'cliente345','tpa200',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (346,'RENTA DE EQUIPOS Y MAQUINARIA, S.A.',26,4,'cliente346','dlk427',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (347,'FERRE ACEROS Y MATERIALES DE CADEREYTA SA DE CV',8,4,'cliente347','bor855',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (348,'GRUPO REALSA EN HERRAMIENTAS S.A. DE C.V.',19,4,'cliente348','xgi573',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (349,'JOSE ALDO SANCHEZ SANCHEZ',6,4,'cliente349','emi288',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (350,'POWER ON DE MEXICO, S.A. DE C.V.',1,3,'cliente350','mrz291',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (351,'LUIS ENRIQUE JIMENEZ MUÑOZ LEDO',8,4,'cliente351','zbt183',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (352,'SANDRA ELIZABETH HERNANDEZ GOMEZ',24,4,'cliente352','mrk155',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (353,'COMPRESORES Y HERRAMIENTAS CARROLL, S.A. DE C.V.',1,5,'cliente353','khi219',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (354,'MARTIN VERDUGO VALENZUELA',1,3,'cliente354','ery194',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (355,'HERRAMIENTAS Y SERVICIOS DE OBREGON S.A. DE C.V.',2,4,'cliente355','yvb733',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (356,'HERRAMAQ PARA LA CONSTRUCCION, S.A. DE C.V.',8,4,'cliente356','zjn141',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (357,'LUZ ADELA BELTRAN RAMOS',13,4,'cliente357','ydp139',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (358,'HERRAMIENTAS Y SERVICIOS DE OBREGON S.A. DE C.V.',2,4,'cliente358','tqh857',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (359,'HERRAMIENTAS Y SERVICIOS DE OBREGON S.A. DE C.V.',2,4,'cliente359','rgr587',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (360,'HERRAMIENTAS Y SERVICIOS DE OBREGON, S.A. DE C.V.',2,4,'cliente360','nfh947',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (361,'HERRAMIENTAS Y SERVICIOS DE OBREGON, S.A. DE C.V.',2,4,'cliente361','ghy428',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (362,'HERRAMIENTAS Y SERVICIOS DE OBREGON S.A. DE C.V.',2,4,'cliente362','jag424',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (363,'COMPAÑIA DE INSUMOS FERRETEROS DEL CENTRO, S.A. DE C.V.',32,4,'cliente363','tim704',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (364,'BUILDER MARTS DE MEXICO S.A. DE C.V.',1,4,'cliente364','agf416',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (365,'LETICIA AURORA PEREZ FERNANDEZ',10,4,'cliente365','xtm914',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (366,'GLORIA LETICIA MORALES DAVILA',8,4,'cliente366','nqz266',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (367,'MECANICA VERDE S.A. DE C.V',10,4,'cliente367','zoq115',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (368,'MULREF, S.A. DE C.V.',26,4,'cliente368','pwi836',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (369,'EXIPORENT SA DE CV',12,4,'cliente369','kvq157',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (370,'FERRETERA CENTRAL DEL GOLFO S.A. DE C.V.',11,4,'cliente370','esm779',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (371,'ROSALES FERNANDEZ BEATRIZ MATILDE',16,4,'cliente371','iut444',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (372,'HERRAMIENTAS Y SERVICIOS DE OBREGON S.A. DE C.V.',13,4,'cliente372','cxk113',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (373,'JULIO CESAR RIVERA MORA',11,4,'cliente373','bbn819',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (374,'DAMCICO S.A. DE C.V.',1,5,'cliente374','sfn614',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (375,'MARCELO DAVILA GONZALEZ',12,3,'cliente375','oki889',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (376,'SUMINISTROS TECNICOS DE MANTENIMIENTO SA DE CV',11,3,'cliente376','bkq842',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (378,'BRAVO MAQ, SA DE CV',26,4,'cliente378','cze643',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (379,'GRUPO VAQUEIRO FERRETERO SA DE CV',19,4,'cliente379','jbi882',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (380,'HERRAMIENTAS Y SERVICIOS DE OBREGON S.A. DE C.V.',2,4,'cliente380','cco123',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (381,'GRUPO VAQUEIRO FERRETERO SA DE CV',19,4,'cliente381','yiu996',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (382,'PAULINO ESTRELLA CHIM',24,4,'cliente382','mew464',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (383,'SOMACO, S.A. DE C.V.',6,4,'cliente383','qku608',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (384,'SERVICIO Y HERRAMIENTAS PARA CONSTRUCCION S.A. DE C.V.',5,4,'cliente384','ljq584',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (385,'SAMUEL LEYVA ALVAREZ',1,4,'cliente385','kwi503',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (386,'JUAN MANUEL CORONA FLORES',1,3,'cliente386','twt329',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (387,'ORLANDO RUIZ RIVERA',1,1,'cliente387','xye403',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (388,'SURTIDORA TAPATIA DE INDUSTRIAS, S.A. DE C.V.',1,4,'cliente388','iqd911',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (389,'COMERCIALIZADORA DE ACEROS ZULA, SA DE CV',29,4,'cliente389','sxy354',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (390,'ALEJANDRO RUIZ LEON',1,4,'cliente390','icz835',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (391,'ORLANDO RUIZ RIVERA',1,4,'cliente391','ich650',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (392,'MIGUEL ANGEL SANCHEZ VARGAS',1,4,'cliente392','ydr912',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (393,'GRUPO VAQUEIRO FERRETERO SA DE CV',24,4,'cliente393','qid122',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (394,'PROVEEDORA DE EQUIPOS Y HERRAMIENTAS .S.A DE.C.V.',2,4,'cliente394','zqx493',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (395,'ROGELIO MARES CASTAÑON',1,3,'cliente395','sht885',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (396,'JOSE GONZALO VALDEZ CORONADO',12,4,'cliente396','tik622',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (397,'IRMA PEDRO OROZCO',11,4,'cliente397','nwh361',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (399,'MARINES ESPINOZA JOSE RAFAEL',8,4,'cliente399','dfx975',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (400,'HERRAMIENTAS, REFACCIONES Y ACCESORIOS S DE RL DE CV',8,3,'cliente400','hfd457',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (401,'SERGIO RODRIGUEZ RODRIGUEZ',20,4,'cliente401','ref769',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (402,'GASES INDUSTRIALES  RAFE S.A. DE C.V.',34,4,'cliente402','mdy553',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (403,'EQUIPO AGROFORESTAL SA DE CV',10,4,'cliente403','lui862',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (404,'FERRETERIA KANTEM SA DE CV',11,5,'cliente404','mxi292',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (405,'GRUPO TUT SA DE CV',6,4,'cliente405','xdw147',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (406,'JOEL CHAVEZ CORTES',26,4,'cliente406','ljr421',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (407,'HAROLD SUAREZ DEL TORO',24,4,'cliente407','ucb509',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (408,'ROSA EUGENIA ANGULO RODRIGUEZ',11,3,'cliente408','stc470',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (409,'GASES Y SOLDADURAS BRINGAS, S.A. DE C.V.',32,3,'cliente409','wty644',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (410,'JUAN DE DIOS VAZQUEZ ORENDAY',32,4,'cliente410','uce806',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (411,'CESAR ROBERTO LOPEZ ALDRETE',13,4,'cliente411','ita685',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (412,'LUGON MAQUINARIA Y EQUIPO PARA CONSTRUCCION S.A. DE C.V.',34,4,'cliente412','bse900',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (413,'REDISA SOLUCIONES S.A. DE C.V.',34,4,'cliente413','oys621',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (414,'HERMOLADO LAGARDA DIAZ',13,1,'cliente414','znq315',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (415,'ELIT GRUPO COMERCIAL SA DE CV',1,4,'cliente415','oua621',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (416,'ISRAEL GONZALEZ MONTES',1,4,'cliente416','cde327',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (417,'HERRAMIENTAS, REFACCIONES Y ACCESORIOS SA DE CV',11,4,'cliente417','onl317',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (418,'AURORA JAUREGUI FLORES',10,4,'cliente418','naa654',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (419,'HILDA MARGARITA ROCHA SANCHEZ',32,3,'cliente419','tlp852',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (420,'LINDER OXIGENO Y ELECTRODOS DE GUADALAJARA SA DE CV',1,3,'cliente420','jgz988',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (421,'REPRESENTACIONES INDUSTRIALES ROBLES S.A.',33,4,'cliente421','fmx774',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (422,'JOSE DEL REFUGIO CAMACHO ALDANA',32,4,'cliente422','udi551',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (423,'GLADYS PERALTA SUAREZ',19,4,'cliente423','euo976',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (424,'MARCO ANTONIO ALARCON ALDRETE',2,4,'cliente424','xzb266',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (425,'GRUPO VAQUEIRO FERRETERO SA DE CV',19,4,'cliente425','ynd655',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (426,'GRUPO VAQUEIRO FERRETERO SA DE CV',19,4,'cliente426','vay354',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (427,'APOLLO COMERCIAL, S.A. DE C.V.',11,3,'cliente427','wkw154',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (428,'CERAMICA Y DECORADOS CANDELARIA SA DE CV',24,4,'cliente428','svm686',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (429,'DIEGO VICENTEÑO ORTIZ',1,1,'cliente429','hkc243',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (430,'ROGELIO FRIAS HERMOSILLO',5,3,'cliente430','izn598',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (431,'SUMINISTROS Y RIEGOS DEL SURESTE SA DE CV',19,3,'cliente431','keu703',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (432,'SERDI SA DE CV',2,4,'cliente432','tmv359',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (433,'MEDINA SAN VICENTE MARCO ANTONIO',33,4,'cliente433','qyg859',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (434,'MAGDALENA BERTADILLO DIMAS',25,4,'cliente434','upd178',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (435,'CARLOS FLORES OLVERA',11,4,'cliente435','hbu509',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (436,'GUSTAVO SILVA ESCOBAR',11,4,'cliente436','jib429',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (437,'TECNOLLITE, SA DE CV',19,4,'cliente437','tzy328',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (438,'BOMBAS MOTORES Y HERRAMIENTAS SA DE CV',19,4,'cliente438','bzc650',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (439,'MARIA DE LA LUZ FLORES BERTADILLO',33,4,'cliente439','ony786',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (440,'ZELMAN JACK LINDOR LARA',2,4,'cliente440','bty257',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (441,'COMERCIAL VAZQUEZ MONTALVO, S.A. DE C.V.',32,4,'cliente441','aej984',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (442,'SERVICIOS Y HERRAMIENTAS DE SINALOA SA DE CV',2,4,'cliente442','zph639',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (443,'CASA MYERS, S.A.',11,4,'cliente443','mzl608',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (444,'BLANCA PATRICIA CERON MONTUFAR',11,4,'cliente444','gkv896',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (445,'MULTISERVICIOS PARA SOLDAR Y CORTAR SA DE CV',3,4,'cliente445','xdf395',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (446,'HERRAMIENTAS PORTATILES DE CHIHUAHUA SA DE CV',11,4,'cliente446','nzb319',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (447,'ENRIQUE ROBLES DIAZ',32,4,'cliente447','exu243',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (448,'FERRETERA MANDIOLA SA DE CV',28,4,'cliente448','nxz809',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (449,'GRUPO VAQUEIRO FERRETERO SA DE CV',19,4,'cliente449','not323',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (450,'INTERNATIONAL TOOL COMPANY, S.A. DE C.V.',1,4,'cliente450','xsa916',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (451,'JESUS AGUSTIN MARTINEZ ALARCON',11,4,'cliente451','btj981',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (452,'LUGON EQUIPOS Y MAQUINARIA DEL BAJIO SA DE CV',34,4,'cliente452','urz796',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (453,'FERREMAQUINARIA INDUSTRIAL SA DE CV',17,4,'cliente453','zrj297',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (454,'MARIA DE LOS ANGELES MARTINEZ TREJO',10,4,'cliente454','tkj909',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (455,'MILENIO DE LUZ SA DE CV',11,4,'cliente455','opq792',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (456,'CONSTRUCCION Y MANTENIMIENTO A EQUIPO DE MEDICION Y CONTROL SA DE CV',19,4,'cliente456','wnk775',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (457,'OBED ARELLANO HURTADO',5,4,'cliente457','hrt650',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (458,'JORGE DEL MORAL VARGAS',11,4,'cliente458','mog843',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (459,'OSORIO PLATA MARCO ANTONIO',33,3,'cliente459','vxc940',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (460,'DAVID CRUZ  SANCHEZ',5,4,'cliente460','kyg262',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (461,'CARLOS DAVID FLORES BERTADILLO',11,4,'cliente461','ncc135',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (462,'PERFILES Y HERRAMIENTAS DE MORELIA SA DE CV',32,4,'cliente462','xgk963',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (463,'GTS INDUSTRIAL SA DE CV',10,4,'cliente463','yre632',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (464,'ELEAZAR SUBIALDEA SANCHEZ',34,4,'cliente464','tru349',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (465,'IRINEO PEDRO HERNANDEZ GARCIA',19,4,'cliente465','zni749',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (466,'SYNERGY IMPORTS SA DE CV',1,4,'cliente466','ymb416',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (467,'GUILLERMINA MORALES MORALES',6,3,'cliente467','crk350',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (468,'MARIA ROMANA SERRA JIMENEZ',19,4,'cliente468','dwg697',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (469,'MARIA TERESA PEREZ AQUINO',34,3,'cliente469','stm168',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (470,'EDUARDO GARCIA JIMENEZ',6,3,'cliente470','nhu107',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (471,'TABSCOOB EQUIPOS DE SEGURIDAD INDUSTRIAL Y SOLDADURA, SA DE CV',19,4,'cliente471','qyr649',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (472,'EUROROBOTS WELDING & CUTTING SA DE CV',11,4,'cliente472','csa858',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (473,'GRUPO FERRETERO CONTINENTAL SA DE CV',24,4,'cliente473','mpm161',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (474,'SOLDADORAS TECNICAS DE MEXICO SA DE CV',11,3,'cliente474','geg499',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (475,'GRUPO REALSA EN HERRAMIENTAS S.A. DE C.V.',33,4,'cliente475','xsd978',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (476,'ARTURO FERNANDO MARTINEZ MIRANDA',28,4,'cliente476','hde140',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (477,'MATILDE LOPEZ AVENDAÑO',24,4,'cliente477','nzv774',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (478,'CANDELARIA CORDOVA LUNA',11,4,'cliente478','dyy381',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (479,'EMPRESA COMERCIALIZADORA ILIMITADA, SA DE CV',6,4,'cliente479','gtf727',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (480,'EFREN LAZCANO GOMEZ',6,4,'cliente480','uid241',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (481,'NANCY ROSALBA ALVAREZ GARCIA',6,4,'cliente481','izt572',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (482,'SOLDADURAS ESPECIALES DEL CARMEN, SA DE CV',19,4,'cliente482','jfb859',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (483,'EDGAR ARTURO FERNANDEZ CHACON',2,4,'cliente483','lgj193',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (484,'JOSE ALDO SANCHEZ SANCHEZ',1,4,'cliente484','ecl887',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (485,'VERONICA RODRIGUEZ RODRIGUEZ',11,4,'cliente485','klb466',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (486,'DAMARIS ALVAREZ CONCHAS',11,3,'cliente486','crt894',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (487,'PROVEEDORA DE CLIMAS Y PARTES S DE RL DE CV',10,4,'cliente487','jpt992',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (488,'HIDRODINAMICA Y SERVICIOS INTEGRALES SA DE CV',19,4,'cliente488','ygx672',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (489,'IGNACIO MARTINEZ MACIAS',11,4,'cliente489','iyh813',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (490,'PEDRO RAIGOZA PEDROZA',11,4,'cliente490','mes374',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (491,'HUMBERTO JOSE MARTINEZ ORTIZ',6,4,'cliente491','sph381',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (492,'MANGUERAS HIDRAULICAS E INDUSTRIALES SA DE CV',11,4,'cliente492','fyl511',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (493,'INTEGRABM SA DE CV',6,4,'cliente493','klz387',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (494,'CLAUDIO  ALONSO RODRIGUEZ GARCIA',11,3,'cliente494','yyz901',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (495,'ERNESTO SANCHEZ',5,4,'cliente495','xdp187',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (496,'MARVIN CASTILLO GUILLEN',5,4,'cliente496','eos686',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (497,'FRANCISCO ARMANDO GARCIA CRUZ',5,4,'cliente497','pgw529',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (498,'FERRETERIA LA PASIEGA S.A. DE C.V.',32,4,'cliente498','unw511',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (499,'MIRTHA LUZ TREVIÑO HERNANDEZ',32,4,'cliente499','oxa275',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (500,'MARIA GUADALUPE RODRIGUEZ OROZCO',32,4,'cliente500','jml958',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (501,'REFACCIONES Y SERVICIOS DOM-REY SA DE CV',34,3,'cliente501','qmh353',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (502,'RVC INSTALACIONES ELECTRICAS SA DE CV',33,4,'cliente502','ebh930',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (503,'SISTEMAS SYDEMAK SA DE CV',34,3,'cliente503','ujq918',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (504,'JULIO CESAR CALDERON MORENO',11,3,'cliente504','fcx416',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (505,'ABASTECEDORA VALLARTA SA DE CV',4,4,'cliente505','bad155',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (506,'CANTU CHAPA RAUL JAVIER',34,4,'cliente506','yph235',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (507,'ALAM JOSE FLORES AGUILAR',10,4,'cliente507','dcc848',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (508,'MARQUEZ ESCOBAR HERMANOS SA DE CV',16,3,'cliente508','vop848',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (509,'CARLA GISELA TORRES LOPEZ',33,4,'cliente509','zfa219',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (510,'FERROMAX SA DE CV',19,4,'cliente510','bsm718',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (511,'CORPORATIVO DE PINTURAS AUTOMOTRICES SA DE CV',33,2,'cliente511','nvv999',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (512,'FLAVIO ANTONIO QUIRARTE MUÑOZ',10,4,'cliente512','kxj493',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (513,'JORGE LUIS ORTEGA TORRES',34,3,'cliente513','jlq413',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (514,'SYSCO INDUSTRIAL SA DE CV',2,4,'cliente514','ftl719',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (515,'JOSE MANUEL CORTINA GARCIA',11,4,'cliente515','stf726',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (516,'ACCESORIOS INDUSTRIALES S.A.',33,10,'cliente516','dbu552',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (517,'VICENTE MARTINEZ DE SANTIAGO',4,4,'cliente517','ksm656',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (518,'OXIGENO Y SOLDADURAS DE JUAREZ SA DE CV',11,4,'cliente518','sxe433',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (519,'ALONSO MARTIN CASTAÑEDA VARGAS',24,4,'cliente519','ocp840',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (520,'HERRAMIENTAS Y SERVICIOS DE OBREGON SA DE CV',13,4,'cliente520','cet260',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (521,'FERRECONSTRUCCIONES DEL SURESTE SA DE CV',24,4,'cliente521','qrj575',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (522,'ARACELI TERUEL RODRIGUEZ',34,3,'cliente522','zgd608',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (523,'PEDRO MARTINEZ ALARCON',4,4,'cliente523','mit471',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (524,'HERRAMIENTAS Y EQUIPOS ARENAS, SA DE CV',6,4,'cliente524','zqu813',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (525,'JOSE GONZALO ALVAREZ SANDOVAL',24,4,'cliente525','whj865',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (526,'JESUS JAVIER FERNANDEZ CHACON',2,3,'cliente526','olm247',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (527,'GAPROSUR SA DE CV',19,4,'cliente527','jhy806',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (528,'BER FERRETERIA SA DE CV',11,4,'cliente528','xku753',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (529,'JESUS GAMANIEL LOPEZ BELTRAN',5,4,'cliente529','oce512',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (530,'MORALES INGENIERIA Y SERVICIOS SA DE CV',34,4,'cliente530','qdu343',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (531,'MANUEL AGUSTIN FLORES ORTIZ',33,3,'cliente531','fvj175',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (532,'ANTONIO VARGAS AGUIRRE',6,4,'cliente532','lxs265',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (533,'MAROVA SURTIDORA INDUSTRIAL SA DE CV',19,4,'cliente533','diy815',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (534,'ALVAREZ DIAZ EVA',34,4,'cliente534','njo706',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (535,'FERRECORRECAMINOS SA DE CV',33,4,'cliente535','xht946',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (536,'HIDROMECANICA Y SISTEMAS DE BOMBEO, S DE RL DE CV',19,4,'cliente536','kky700',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (537,'ABEL ADRIAN ROJAS PEREZ',6,4,'cliente537','jby478',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (538,'ALIALLOYS SA DE CV',34,4,'cliente538','jfb887',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (539,'GILBERTO HERNANDEZ OSUNA',2,3,'cliente539','pze677',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (540,'FESA DISTRIBUCIONES DE LA CONSTRUCCION SA DE CV',2,4,'cliente540','dsk815',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (541,'COMERCIAL FERRETERA ERMITA SA DE CV',33,4,'cliente541','ezp389',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (542,'FRANKLIN GAMALIEL CARBALLO MASSA',24,4,'cliente542','apn899',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (543,'INDUSTRIAS VAZQUEZ SA DE CV',13,4,'cliente543','xus190',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (544,'MERCADO DE LA SOLDADURA DEL SURESTE SA DE CV',19,4,'cliente544','dhc406',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (545,'MATERIALES DE CONSTRUCCION DE LOS ALTOS SA DE CV',19,4,'cliente545','twk965',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (546,'BENJAMIN ARREDONDO AYALA',5,4,'cliente546','cik657',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (547,'FERRETERIA Y MATERIALES EL PARAISO, SA DE CV',6,2,'cliente547','fvj420',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (548,'DANIEL MONTIEL CARRANZA',6,4,'cliente548','rqg431',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (549,'GRUPO VAQUEIRO FERRETERO SA DE CV',19,4,'cliente549','wiv616',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (550,'COMERCIALIZADORA DE MAQUINARIA Y EQUIPO MECANICO SA DE CV',19,4,'cliente550','wrb124',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (551,'OXISOL SA DE CV',11,4,'cliente551','zsj985',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (552,'INDUSTRIAS VAZQUEZ SA DE CV',2,4,'cliente552','sst468',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (553,'FERRETERIA SIEBER SA DE CV',34,4,'cliente553','dop494',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (554,'GOVIR HERRAMIENTAS SA DE CV',34,4,'cliente554','ivw435',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (555,'OXWELD SA DE CV',34,4,'cliente555','wky361',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (556,'AUTOGENA DE HIDALGO SA DE CV',11,4,'cliente556','nhl696',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (557,'LETICIA CALDERON AYALA',6,4,'cliente557','bes658',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (558,'SOLMA WELD SA DE CV',32,4,'cliente558','rkc252',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (559,'DISQRO S DE RL DE CV',5,4,'cliente559','sxh184',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (560,'FERRETERIA LA CURVA T.H. SA DE CV',6,4,'cliente560','hxr878',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (561,'GRUPO INDUSTRIAL SOGAMA SA DE CV',19,4,'cliente561','szh152',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (562,'EDUARDO CEBALLOS MURILLO',2,3,'cliente562','zyy957',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (563,'ONO KISHIGAMI ARMANDO',11,4,'cliente563','rqw347',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (564,'MULTI-RENT SERVICES SA DE CV',19,4,'cliente564','lkq273',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (565,'GASES Y ELECTRODOS LUMA DE LOS MOCHIS SA DE CV',11,4,'cliente565','mol855',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (566,'RAQUEL GOMEZ PREGOS',28,4,'cliente566','xhi495',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (567,'NORMA PATRICIA SOLIS RUIZ',28,4,'cliente567','sxd979',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (568,'DANIEL MONTIEL CARRANZA',11,4,'cliente568','mjc796',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (569,'RUTH BELEN JUAREZ ZENTENO',28,4,'cliente569','rmc853',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (570,'ACEROS MURILLO SA DE CV',10,4,'cliente570','pbe361',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (571,'FERRETERIA POPULAR DEL NORTE SA DE CV',22,4,'cliente571','ize882',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (572,'ROBERTO YAÑEZ FABELA',11,4,'cliente572','arl501',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (573,'MARIBEL AVALOS LOPEZ',6,4,'cliente573','orw306',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (574,'JESUS DIAZ VERGARA',19,4,'cliente574','djb132',true);
insert into client (id,name,agent,price_list,username,passwd,active) values (9999,'CONSTRUCCION Y MULTISERVICIOS BAFSA SA DE CV',1,3,'cliente9999','nap899',true);
select * from client;